spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/CLIENT_DB
#    url: jdbc:mysql://host.docker.internal:3306/CLIENT_DB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registryWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.int}
auth:
  secretKey: secret1234
  service:
    url: http://localhost:9092/api-gateway/auth-service