spring:
  application:
    name: customer
  datasource:
#    url: jdbc:mysql://localhost:3306/CLIENT_DB
    url: jdbc:mysql://host.docker.internal:3306/CLIENT_DB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}