server:
  port: 8082
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3307/AUTH_DB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    enabled: true
    fetchRegistry: true
    registryWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.int}

token:
  expirationTime: 36000000
  secretKey: secret1234