server:
  port: 9092
  servlet:
    context-path: /api-gateway
spring:
  application:
    name: api-gateway
eureka:
  client:
    fetchRegistry: true
    registryWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.int}
zuul:
  sensitive-headers: Cookie
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831